/*
 * Session cookie — Phase 2: Auth/Security, upgraded by Sprint 3a (Session
 * Security Foundation).
 *
 * Signed JWT in an httpOnly cookie, now referencing a DB-backed Session
 * row via a `sid` claim (SPRINT_3A_SESSION_SECURITY_PLAN.md). Signed and
 * verified with `jose` (HS256), which runs on both the Node and Edge
 * runtimes — required because proxy.js verifies this same token and
 * Next.js middleware runs on the Edge runtime by default.
 *
 * EDGE-SAFETY CONTRACT: this module must never import Prisma or any
 * Node-only module. verifySession() stays purely cryptographic (signature
 * + expiry + claim-shape checks, no DB) so proxy.js can keep calling it
 * unchanged. The DB-backed validation (Session row exists / not revoked /
 * not expired / user active, role from the DB) lives in
 * lib/admin/auth/sessionService.js and is consulted only from the Node
 * runtime via lib/admin/auth/authorize.js.
 *
 * Sprint 3a fail-closed rule: verifySession() requires a well-formed
 * UUID `sid` claim. Legacy tokens issued before this sprint carry no sid
 * and are rejected here — at the Edge and in Node alike — forcing a
 * documented one-time re-login after deployment. No dual-accept/grace
 * mode: accepting sid-less tokens would recreate the unrevocable-session
 * hole this sprint closes.
 *
 * Nothing here trusts client input: verifySession() always re-checks the
 * cryptographic signature and expiry before returning a payload. Every
 * caller (proxy.js, lib/admin/auth/authorize.js) treats an invalid or
 * missing token as "not logged in," never as a role to fall back on. The
 * `role` claim is kept in the token solely so old/new token shapes stay
 * similar — it is decorative; no authorization decision reads it (the DB
 * User row is the only role source, see authorize.js/sessionService.js).
 */

import { SignJWT, jwtVerify } from 'jose';

export const SESSION_COOKIE_NAME = process.env.SESSION_COOKIE_NAME || 'admin_session';

/**
 * Single source of truth for session lifetime. Exported (Sprint 3a) so
 * sessionService derives the Session row's `expiresAt` from the exact
 * same value as the JWT `exp` — DB and token expiry never diverge.
 */
export const SESSION_MAX_AGE_SECONDS = Number(process.env.SESSION_MAX_AGE_SECONDS) || 8 * 60 * 60; // 8h

// crypto.randomUUID() output shape (RFC 4122 v4). Used to require a
// well-formed sid claim — anything else fails closed. Edge-safe: plain
// regex, no imports.
const SID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

function getSecretKey() {
  const secret = process.env.SESSION_SECRET;
  if (!secret) {
    throw new Error(
      '[lib/admin/auth/session] SESSION_SECRET is not set. Add it to .env.local ' +
        '(see .env.local.example) before logging in — never commit a real value.'
    );
  }
  return new TextEncoder().encode(secret);
}

/**
 * Sign a new session JWT. Sprint 3a: `sid` is REQUIRED — it references the
 * DB Session row created by the login route, and issuing a token without
 * one would mint an unrevocable session (the exact hole this sprint
 * closes), so signing fails closed instead. The sid is generated by
 * sessionService (CSPRNG), never here.
 */
export async function signSession({ userId, role, sid }) {
  if (typeof sid !== 'string' || !SID_REGEX.test(sid)) {
    throw new Error('[lib/admin/auth/session] signSession requires a well-formed sid.');
  }
  return new SignJWT({ role, sid })
    .setProtectedHeader({ alg: 'HS256' })
    .setSubject(userId)
    .setIssuedAt()
    .setExpirationTime(`${SESSION_MAX_AGE_SECONDS}s`)
    .sign(getSecretKey());
}

/**
 * Verify a session JWT. Returns { userId, role, sid } on success, or null
 * on any failure (missing token, bad signature, expired, malformed,
 * missing/malformed sid — legacy pre-Sprint-3a tokens fail here) — callers
 * must treat null as "not authenticated," not throw a 500.
 *
 * This is only the cryptographic half of authentication: a non-null
 * result proves the token was validly issued, NOT that the session is
 * still alive. Node callers must go through authorize.getSessionUser(),
 * which additionally checks the Session row and User row in the DB.
 */
export async function verifySession(token) {
  if (!token) return null;
  try {
    const { payload } = await jwtVerify(token, getSecretKey());
    if (!payload.sub || !payload.role) return null;
    if (typeof payload.sid !== 'string' || !SID_REGEX.test(payload.sid)) return null;
    return { userId: payload.sub, role: payload.role, sid: payload.sid };
  } catch {
    return null;
  }
}

/** Cookie options shared by the login route (set) and logout route (clear). */
export function getSessionCookieOptions() {
  return {
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production',
    sameSite: 'lax',
    path: '/',
    maxAge: SESSION_MAX_AGE_SECONDS,
  };
}
